### ISSUE TITLE
positioning difficult

### ISSUE THREAD

**Issue by jinmatt** [techatspree/jquery-toastmessage-plugin#3]
I'm not able to position the dialogs onto the left side, like top-left, bottom-left, etc. Is this a issue or the author have not provided these options?

**Comment by daniel-tonn** [comment]
Hi,

the missing positons were just not defined in the css yet. I will add the missing  positions, that finally we will have the following options for positions:

top-left
top-center
top-right
middle-left
middle-center
middle-right

**Comment by daniel-tonn** [comment]
consolidated values for positions-parameter to the following values: top-left, top-center, top-right, middle-left, middle-center, middle-right
